---
# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

heading-style:
  style: atx
ul-style:
  style: dash
no-hard-tabs:
  spaces_per_tab: 2
line-length:
  # Semantic Line Breaks strategy: One clause per line.
  # Prioritize logical structure and readable diffs over strict wrapping.
  # https://sembr.org/
  line_length: 80
  severity: warning
no-duplicate-heading:
  siblings_only: true # Allow duplicate headings in CHANGELOG
no-trailing-punctuation:
  punctuation: ".,;:。，；:" # List of not allowed
no-bare-urls: false
first-line-h1:
  allow_preamble: true
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: underscore
strong-style:
  style: asterisk
